### ISSUE TITLE
A Multitude of Issues While Testing

### ISSUE THREAD

**Issue by G-i-o** [backmeupplz/shieldy#102]
Hi.

I have created a private testing chat group to test this before adding it to our public group and found the following problems.

FIRST SCENARIO: Group owner (A)  promotes Shieldy as admin. Another member (B) joins the chat and acts as the tester. A is able to apparently configure the bot and everything seem to go well. Yet when the B tests the bot by leaving the chat and rejoining it:
- B (re) join the chat and it's presented with the right captcha. B solves the captcha, messages are deleted as supposed but **welcoming message is not shown**. The configuration, though, shows that it's set correctly.
- Following previous point, **buttons with links are also not shown**. Again, configuration shows they are set up correctly.

SECOND SCENARIO: Following previous scenario, A & B switch. B becomes owner of the group and A the testing member.
The configuration is left untouched.
- Again, the captcha is presented but no following welcoming message neither linked buttons.
- To aggravate, **now neither B nor A are able to interact with the bot in any way**. All attempts (ie. /help or /viewconfig etc.) are deleted.

I have tried to make the group chat public but got the same results.

If necessary for testing, I can provide invitation link for the group.

Thank YOU.

**Comment by backmeupplz** [comment]
Hi there!

1. You should always config Shieldy **in the groups**, not in private messages. I.e. the id in `/viewConfig` should be negative.
2. Shieldy experiences issues at the moment, follow https://t.me/borodutch_support for updates.

Cheers!

**Comment by G-i-o** [comment]
Hi @backmeupplz ,

Thank YOU for your prompt reply. Much appreciated.

Sorry I was not clear. I said "private testing" not "Private messages" or chat.

I did indeed worked with Shieldy in a group, private group. Groups in Telegram can be "Private" or "Public". I tested it on both. The groups were created purposely by me for the testing.

I hope makes is more clear now.

I will also follow your updates.

**Comment by backmeupplz** [comment]
@G-i-o can you share a `/viewConfig` example with me here, please?

**Comment by G-i-o** [comment]
@backmeupplz 
I'd be happy to but, as mentioned above, currently any interaction with the bot gets deleted with no results given.
So, if I type `/viewConfig` or any other command, the post gets deleted and nothing shows up.`

**Comment by backmeupplz** [comment]
@G-i-o can you give me a link to the group then? Better to send it to me on Telegram — t.me/borodutch

**Comment by G-i-o** [comment]
@backmeupplz 
Sure. Done. Thank YOU.
