### ISSUE TITLE
Captcha image not working

### ISSUE THREAD

**Issue by bitog** [backmeupplz/shieldy#104]
I self host shieldy and all captcha option work fine just the image one is not doing anything. Any idea what the cause could be?

**Comment by backmeupplz** [comment]
Don't forget to install headless Chrome to support https://www.npmjs.com/package/convert-svg-to-png :)

**Comment by bitog** [comment]
I am running it on an Ubuntu server. I googled it but was not really able to find a way to install `headless Chrome`. Do you know of any? Thank you!

**Comment by backmeupplz** [comment]
@bitog interesting. Shieldy runs on Ubuntu server and I installed it there :) I think it was https://github.com/puppeteer/puppeteer/
