### ISSUE TITLE
Users are banned no matter how /banUsers is set

### ISSUE THREAD

**Issue by simgislab** [backmeupplz/shieldy#106]
No matter whether it was to kick or ban a user, users are always blacklisted.

Is this correct? Shouldn't `banUsers: false` allow users to try joining more times?

**Comment by backmeupplz** [comment]
`banUsers: false` bans a user for 30 seconds. This is how you kick on Telegram.

**Comment by simgislab** [comment]
`banUsers: false` case

1. User tries to join a group
2. Fails to answer captcha
3. Kicked/banned by Shieldy
4. Added to blacklist <- !!! indefinitely !!! (just checked, tested in the morning, still on blacklist)
5. When trying to access the same group user always gets 'Sorry, this chat does not seem to exist message'

Am I missing something?

**Comment by backmeupplz** [comment]
You are, `banUsers: false` bans a user for 30 seconds. https://github.com/backmeupplz/shieldy/blob/fb346ef132acd42bd64aafa13a63170568d3efee/src/helpers/newcomers.ts#L297.

Make sure to set `banUsers` option in the group chat, not in the private messages with the bot. Changing this option only affects future user joins.
