### ISSUE TITLE
greetingButtons setting through /setConfig does not work

### ISSUE THREAD

**Issue by tedescolor** [backmeupplz/shieldy#108]
The message 

/setConfig
language: it
captchaType: button
timeGiven: 180
adminLocked: false
restrict: false
noChannelLinks: false
deleteEntryMessages: false
greetsUsers: true
customCaptchaMessage: false
strict: true
deleteGreetingTime: 60
banUsers: false
deleteEntryOnKick: true
cas: true
underAttack: false
noAttack: false
buttonText: Entra!
allowInvitingBots: false
skipOldUsers: false
skipVerifiedUsers: false
greetingButtons:
DuckDuckGo - https://duckduckgo.com
Wikipedia - https://wikipedia.com

change everything I set but greetingButtons.

**Comment by backmeupplz** [comment]
Thanks for the report, I don't think I'll add setting greeting buttons, sorry, a bit too complicated ;)
