### ISSUE TITLE
no response to commands

### ISSUE THREAD

**Issue by boistordu** [backmeupplz/shieldy#111]
Since a few days now, I can't get shieldy respond to my commands. 
it would be nice to actually be able to do /help@shieldy_bot in cas of multiple bots in the channel.
I was trying to do a /setConfig timeGiven: 120 and it doesn't work. Do I need to do each time a copy paste of the entire config to change just one small element? 
It would be great to have wiki ...

**Comment by backmeupplz** [comment]
`/setConfig timeGiven: 120` works well. `/help@shieldy_bot` works well. You can always start a wiki :) it's an open-source project, feel free to submit a pull request!

P.S., if Shieldy has /lock option on, then only admins can configure it.
