### ISSUE TITLE
Does not kick unresponsive users

### ISSUE THREAD

**Issue by Romern** [backmeupplz/shieldy#112]
If a user does not solve the captcha or press the button in the required time, he is not kicked since a few days (? could be just since today). Deleting messages still works though.

**Comment by Romern** [comment]
Seems to be fixed by https://github.com/backmeupplz/shieldy/commit/7def5f90ae522aec26cbe57fea8996a4f5f233c0

**Comment by DASPRiD** [comment]
@Romern Can it be that this fix is not deployed to @shieldy_bot on Telegram? I found at least 3 bots in our chat of which the join message got deleted, but they were not kicked. Most recently 15 minutes ago.

**Comment by backmeupplz** [comment]
@DASPRiD check recent messages to see if they passed captcha. Shieldy should be running well at the moment

**Comment by Romern** [comment]
Seems to work fine for me currently.
