### ISSUE TITLE
Allow more time options for /restrict 

### ISSUE THREAD

**Issue by MaximilianR** [backmeupplz/shieldy#118]
It seems some bots wait for more than 24 hours before posting spam with links, and it would be very useful to be able to increase /restrict with the 24 hour limit to 36h, 48h etc., increasing the chance these bots are banned (as they spam in other Telegram channels likely) before their restriction is lifted in the channel where I use Shieldy.

Btw Shieldy is the best bot there is on Telegram hands down, thank you so much for it!

**Comment by backmeupplz** [comment]
Hm, sounds like a great idea to implement. Thank you for the kind words and the suggestion!

**Comment by backmeupplz** [comment]
@MaximilianR now you can set it with the `/restrictTime 48` command :) Thank you a lot for the suggestion again!

**Comment by MaximilianR** [comment]
Ty, you are the man!
