### ISSUE TITLE
Docker-Compose not working

### ISSUE THREAD

**Issue by DolanKivert** [backmeupplz/shieldy#119]
hi

Had a bit of a problem getting the docker compose-script to work out of the box, since version 3 seemst to not support secrets in the way they are used, changing it to version 3.1 worked just fine for me though.

**Comment by backmeupplz** [comment]
Interesting, can you submit a PR with the fix, please?

**Comment by backmeupplz** [comment]
@masaruhoshi maybe you can help out here a bit? :)
