### ISSUE TITLE
Mongo errors "cannot remove from a capped collection"

### ISSUE THREAD

**Issue by azhiltsov** [backmeupplz/shieldy#124]
Hi. 

I am hosting the shieldy bot and dedicated instance of Mongo for it.
Every minute I observe the next error in the Mongo logs:

```
{"t":{"$date":"2021-01-13T09:20:46.661+01:00"},"s":"I", "c":"STORAGE", "id":20291, "ctx":"TTLMonitor","msg":"failing remove on a capped ns","attr":{"namespace":"shieldy.cappedmessages"}}
{"t":{"$date":"2021-01-13T09:20:46.661+01:00"},"s":"E", "c":"INDEX", "id":22538, "ctx":"TTLMonitor","msg":"Error processing TTL index","attr":{"index":{"v":2,"key":{"createdAtForExpiry":1},"name":"createdAtForExpiry_1","expireAfterSeconds":120,"background":true},"error":{"code":10089,"codeName":"Location10089","errmsg":"cannot remove from a capped collection"}}}

```
My guess those are shieldy related, but my scarce knowledge of Mongo does not allow me to troubleshoot. 
Please advise.

**Comment by backmeupplz** [comment]
For some reason your Mongo instance doesn't want to remove `CappedMessage` that is supposed to live only for 2 minutes. I don't see such issues on the production instance of Shieldy so I probably won't be able to help. Try wiping the CappedMessage collection? Maybe it's an old CappedMessage that doesn't want to be removed for some reason?
