### ISSUE TITLE
Feature suggestion: /trustMembersInvitations

### ISSUE THREAD

**Issue by samuelgrigolato** [backmeupplz/shieldy#135]
Let's say I join group X. Shieldy displays me a captcha prompt. After filling in the captcha I invite user A.

Wouldn't it be reasonable to trust me and avoid bothering user A with a captcha question? Would this be possible to develop as a group specific setting? I wonder if Telegram API makes it visible if a user joined via invitation from another user or directly via search/external link, as this of course would be necessary for this addition.

**Comment by backmeupplz** [comment]
Nope, it wouldn't. Spammers inviting other spammers is a common attach vector.

**Comment by samuelgrigolato** [comment]
Just so I can understand, in the idea I proposed the first spammer would have to fill in the captcha before being allowed to invite others in a "trusted" manner. How do you picture they being able to abuse this? One extra barrier could be limiting trusted invites to, let's say, one per day or something like that.

To give you a bit of context: this happened in a group of mine were a legitimate user failed to fill in the captcha after being invited by a trusted member. This event was the motivation behind this feature suggestion.

**Comment by backmeupplz** [comment]
> One extra barrier could be limitting trusted invites to, let's say, one per day or something like that.
See, you're already trying to "patch" this solution :)

The attack vector is simple: a human-spammer joins a group, then the human-spammer invites thousands of bot-spammer accounts. Then you will have to weed these spammer accounts manually.

**Comment by samuelgrigolato** [comment]
> See, you're already trying to "patch" this solution :)

That's fair enough, thanks for taking the time to explain it in further details.

Even considering the necessity of "patching the patch" I can see some room for improvement when it comes to trusted member invites. Of course the machinery to make this work would probably get out of hand real quick and because of that not being worth the effort. In any case the bot is still a net positive and we are still happily using it :).
