### ISSUE TITLE
Shieldy not removing new joinee messages after verification step

### ISSUE THREAD

**Issue by GAUTAMRAJU15** [backmeupplz/shieldy#139]
Hi! I decided to add Shieldy bot to a telegram channel https://t.me/dmscriptgroup ( still there ). Whenever a new user joins in, it asks to solve a math puzzle, But the problem is after submitting, it doesn't remove the user's answer. I have to manually remove all those numbers. 
Any help would be appreciated. Thanks!

**Comment by backmeupplz** [comment]
Make sure Shieldy is an admin.
