### ISSUE TITLE
Compatible with "-" language key

### ISSUE THREAD

**Issue by kslr** [backmeupplz/shieldy#14]
such as zh-CN

In addition, how do you feel about adding mathematical formulas?

**Comment by backmeupplz** [comment]
Nothing in the codebase should prevent one from adding locales with `-` in their language key :)

As for math formulas: Shieldy already supports `digits` captcha which is still not breached by spammers but easy enough for humans to be let through :) increasing the difficulty of digits captcha will not stop spammers if they get through but will complicate things for humans
