### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by darkayme60** [backmeupplz/shieldy#19]
Hello can you add french language plz?
Translation:
Digits:(Number+Number)(Name), merci d'envoyer la solution de l'équation dans le temps imparti sur ce groupe où vous serez banni.merci! (Time)
Simple: (name)merci d'envoyer un message dans le temps imparti où vous serez banni(time)
Button: (name)merci de cliquer sur le bouton dans le temps imparti où vous serez banni (time)
Thank you ;)

**Comment by backmeupplz** [comment]
Can you translate all the english strings, please? :)

**Comment by backmeupplz** [comment]
https://github.com/backmeupplz/shieldy/blob/master/src/helpers/strings.ts — here's the file

**Comment by backmeupplz** [comment]
please, reopen the issue if you want to work on it ;)
