### ISSUE TITLE
More human-readable wording in greeting

### ISSUE THREAD

**Issue by maximal** [backmeupplz/shieldy#20]
For example, in Russian:

> @username, пожалуйста, отправьте любое сообщение в этот чат в течение указанного времени, иначе вы будете кикнуты. Спасибо! (240 сек)

↓

> @username, пожалуйста, отправьте любое сообщение в этот чат в течение **240 сек**, иначе вы будете кикнуты. Спасибо!

**Comment by backmeupplz** [comment]
Would be great but I'm to lazy

**Comment by maximal** [comment]
Where is the message template?

**Comment by backmeupplz** [comment]
All three phrases are here: https://github.com/backmeupplz/shieldy/blob/5a22839f4c35753ed15c256ef041be7f8beeff80/src/helpers/strings.ts#L344, it's used here: https://github.com/backmeupplz/shieldy/blob/5a22839f4c35753ed15c256ef041be7f8beeff80/src/helpers/newcomers.ts#L278

**Comment by SVETaMan** [comment]
А

**Comment by backmeupplz** [comment]
I've added `/customCaptchaMessage` command :) hope it's sufficient.
