### ISSUE TITLE
More options for time waiting to verification

### ISSUE THREAD

**Issue by KlausDevWalker** [backmeupplz/shieldy#21]
You could add buttons (like "-" and "+" and/or "sec", "min", "hour") so we can customize it in a better way. The present option is kicking users too fast before they participate. My group is a small one, so people subscribe, see that it's no active convo and go somewhere else and don't see that it's been asked them to take some action.

**Comment by backmeupplz** [comment]
Should now be available by using the command like `/timeLimit 7200`. Let me know if it works, cheers.
