### ISSUE TITLE
Feature request: auto-delete greeting messages

### ISSUE THREAD

**Issue by Shulyaka** [backmeupplz/shieldy#22]
Hi!

Because people tend to join chats just for reading, the greeting messages usually flood the chat. It would be awesome if Shieldy could remove all its greetings after a set period of time (e.g. 3 min, which is enough time for an average person to understand he/she is welcome).
Shieldy is nice, but its messages are not usually in line with actual chat topic and other discussions in the chat. It would be nicer if it could do its job under the hood as much as possible. The best technology is invisible.

**Comment by chaseblackmon** [comment]
Couldn't agree more. It could be as simple as a command /shieldy silentgreeting 3m

**Comment by backmeupplz** [comment]
kekeke if it's that simple, feel free to submit a pull request

**Comment by backmeupplz** [comment]
Done, please, use `/deleteGreetingTime 100` command. Cheers!
