### ISSUE TITLE
Unban user after time runs out

### ISSUE THREAD

**Issue by BiroStorm** [backmeupplz/shieldy#24]
Hello,

I just discovered that if the bot kicks out a user, the user will be unban (or unlimited) and can rejoin the group without limitations.
To simulate, it's very simple:

- Set up the bot to kick if user doesn't solve the CAPTCHA.

- Lets someone joins the group and manually (or with another bot) ban him from the group 

- after the time runs out wait few seconds and the user should be able to join the group again

I recreated this bug multiple times and it can cause conflict with other bot (like antistormbot) that ban immediately Arab users or userbot.

Thanks.

**Comment by backmeupplz** [comment]
It's not a bug, it's a feature. Shieldy kicks users, it doesn't ban them.

**Comment by BiroStorm** [comment]
Exactly, Shieldy kicks users but to do that automatically unban the user if he is already banned.
This is what I mean ^^''

**Comment by backmeupplz** [comment]
Oh, I see what you mean. Yeah, it's a known issue, I'm working on it

**Comment by backmeupplz** [comment]
Alright, after investigation I've found that Shieldy might interfere with other bots by unbanning them (it kicks users, doesn't ban them). So I've introduced `/banUsers` command that will ban the users forever instead :)
