### ISSUE TITLE
Feature request: Add simple internal group statistics.

### ISSUE THREAD

**Issue by pakLebah** [backmeupplz/shieldy#30]
My group needs to evaluate members activity periodically. So, we need some kind of members activity statistics. But we don't want to use those fancy and over-complicated stats-bot like the ones popular out there. We simply need these informations:

1. Number of **total** messages sent into the group within a time period.
2. Number of **total** members involved in the conversation within a time period.
3. A few of most **active** members in the group within a time period.
4. A few of most **inactive** members in the group within a time period.

Say, the command is `/stats` which would produce output like this:

> **Group Statistics**
> 
> Within the last _30_ days, there are **871** messages sent into this group by **26** members involved in the conversation of **40** registered members.
> 
> The most _10_ active members are: 
> 1. username_1 (x messages)
> 2. username_2 (x messages)
> 3. username_3 (x messages)
> 4. username_4 (x messages)
> 5. username_5 (x messages)
> 6. username_6 (x messages)
> 7. username_7 (x messages)
> 8. username_8 (x messages)
> 9. username_9 (x messages)
> 10. username_10 (x messages)
> 
> The most _10_ inactive members are:
> 1. @userid_1 (x messages)
> 2. @userid_2 (x messages)
> 3. @userid_3 (x messages)
> 4. @userid_4 (x messages)
> 5. @userid_5 (x messages)
> 6. @userid_6 (x messages)
> 7. @userid_7 (x messages)
> 8. @userid_8 (x messages)
> 9. @userid_9 (x messages)
> 10. @userid_10 (x messages)
> 
> Any members who send less than 5 messages within last _30_ days will be kicked out from this group. This group forbids silent readers. You have been warned!

Configuration:
`/stat_period` = 30 (days)
`/stat_active` = 10 (members)
`/stat_inactive` = 10 (members)
`/stat_statement` = "Any members who send less than 5 messages within last _$period_ days will be kicked out from this group. This group forbids silent readers. You have been warned!"

Please note that the inactive members list does mention the members so they get the notification. If you like, you could set this as config as well, such as `/notify_inactive`.

I hope this request will be implemented. Thank you.

**Comment by backmeupplz** [comment]
Sounds like an entire separate bot. Sorry, but this function is out of scope for @shielfy_bot. But thank you for suggestion.
