### ISSUE TITLE
Feature request: Remove deleted account and last seen long time ago.

### ISSUE THREAD

**Issue by pakLebah** [backmeupplz/shieldy#31]
In most large groups, it's common to see lots of inactive or deleted accounts and inactive users who haven't been logged in to Telegram for a long time. These people are junks to the group and create false data of real members of the group. So, could you provide a command to remove deleted account and members who last seen is long time ago? I propose `/remove_deleted_account` and `/remove_inactive_account` accordingly.

What do you think? Is it possible to be done by a bot? Thank you.

**Comment by backmeupplz** [comment]
There are existing solutions on Telegram that can already do this :) but thanks for the suggestion

**Comment by pakLebah** [comment]
The existing solution is to remove them one by one. In large groups with hundreds or even thousands of members, it's practically undoable. These proposed commands remove them altogether.

**Comment by backmeupplz** [comment]
@pakLebah try https://t.me/crosser_bot ;)

**Comment by pakLebah** [comment]
It looks like what I need. Unfortunately, it only speaks in Russian. I wish it also speaks in English too, at least. 😓
