### ISSUE TITLE
[Feature Request] Ban users if it is the second time they haven't passed the captcha

### ISSUE THREAD

**Issue by MarcAnt01** [backmeupplz/shieldy#35]
I think the first time the user should be kicked since they might not have understood about the captcha, but the second time it'll be better to ban them

**Comment by backmeupplz** [comment]
Shieldy deletes all the records of the newcomers who don't pass the captcha, so it's fine if they try to join again and again. Also, you can use `/banUsers`, if you want.

**Comment by MarcAnt01** [comment]
> Shieldy deletes all the records of the newcomers who don't pass the captcha, so it's fine if they try to join again and again. Also, you can use `/banUsers`, if you want.

Thanks, I was aware of that possibility, just would like to make a feature request, but I have understood it isn't technically possible
