### ISSUE TITLE
Users doesnt blocking

### ISSUE THREAD

**Issue by mmoustache** [backmeupplz/shieldy#39]
Hello, when spamer adds to group and making fast message it shows to all users and captcha doesnt work.

Yes, after timeout user where kicked or banned, but before this action spamer can make a spam.

It will be great to delete all messages of spam user with kicking after failed captcha.

**Comment by mmoustache** [comment]
Знаю, что есть поддержка на русском. Я хотел сказать следующее:

1. Когда спамер добавляется в группу, то при всех включенных ограничения и настройках бота, спамер может спокойно оправить сообщение или несколько без прохождения капчи.

2. После истечения срока капчи спамер киквется, а все его сообщения остаются, что кажется совсем странным.

Было бы круто в есте с киком удалять сообщения ещеоставил спамер

**Comment by backmeupplz** [comment]
@mmoustache пользуйтесь /restrict и /strict, ну и не забудьте дать боту админку.

**Comment by mmoustache** [comment]
Все эти команды введены и админка дана, спамерв успевают при входе закинуть сообщения прежде чем бот попросит из ввести капчу, а после кика сообщения спикеров остаются, притом, что бот легко удаляет и приветствия и Entry message

**Comment by backmeupplz** [comment]
@mmoustache киньте ссылку на группу :) давно не видел такого поведения

**Comment by mmoustache** [comment]
Вот создал для теста и в ней все происходит @tstgrpbtlr

**Comment by backmeupplz** [comment]
@mmoustache какой тип капчи вы используете? Боты очень просто обходят простую капчу, советую использовать капчу цифровую — там точно работают /strict и /restrict
