### ISSUE TITLE
Minor issue with command explanation

### ISSUE THREAD

**Issue by NocturneBlock** [backmeupplz/shieldy#41]
Hi, I just installed Shieldy Bot, and I am happy with it overall- there is one command that I don't think is documented well, and might be able to use some modification, depending on how it actually works.
Does /deleteEntryMessages delete all entry messages, or only ones from the users who fail the captcha?

**Comment by backmeupplz** [comment]
@NocturneBlock all of them, I'm working on the feature to delete only the entry messages from people who failed captcha. Subscribe to https://t.me/borodutch_support, I'll publish an update there.
