### ISSUE TITLE
Bug: Bot not accepting custom greetings

### ISSUE THREAD

**Issue by NocturneBlock** [backmeupplz/shieldy#42]
Pretty much what it says on the tin. I used the /customCaptchaMessage command, and got the prompt to respond with my new message, but then nothing happens once I reply, and the bot continues to use the default message. If I use the command again, it says it is going back to the default. I have tried messages with and without using the variables, and of three different lengths (kept making it shorter in case that was the problem).

**Comment by backmeupplz** [comment]
@NocturneBlock make sure to **reply** and not just send the message ;) also make sure to use `$equation` and `$seconds` if you use `digits` captcha.

**Comment by NocturneBlock** [comment]
Ah, fair enough. Might tie into the "please be more clear in the instructions" issue I posted. Thanks for the feedback, though!

**Comment by ruiflcruz** [comment]
I can't seem to get the greetings message to work. Yes I replied to the bot with the custom message, I removed links and stuff that might prevent the message from being sent but still no success. Any suggestion?
