### ISSUE TITLE
Adding Japanese language

### ISSUE THREAD

**Issue by hanzoh1** [backmeupplz/shieldy#44]
Hi @backmeupplz backmeupplz !

I'm using shieldy for my community where Japanese people are majority.
Is there anyway, you can add Japanese translation in shieldy?

I am happy to do any translation but I am non-dev and have no idea where and how to make use of your open sourecode.

Thanks!

**Comment by backmeupplz** [comment]
Hello @hanzoh1,

Please, find the translation file here: https://github.com/backmeupplz/shieldy/blob/master/src/helpers/strings.ts. It would be great if you could translate the `en` texts to Japanese and send them to me either to https://t.me/borodutch or to n@borodutch.com.

Thank you!
