### ISSUE TITLE
Request: Option to have kick messages deleted, as well as entry.

### ISSUE THREAD

**Issue by NocturneBlock** [backmeupplz/shieldy#52]
I appreciate the inclusion of the command to delete the entry message of beings that have been booted due to failing the captcha. I would like to be able to also auto-delete the removal messages (separate from the delete entry message option), as my channel is getting so inundated that the messages are disrupting the log. It's better with the entry messages removed, but I would like to be able to make it a non-event if you didn't notice while it was happening. Some people might like to leave them, which is why I think it should be a separate option.

Thank you very much for making Shieldy!

**Comment by backmeupplz** [comment]
Hm, interesting. I'll see what I can do.

**Comment by FiveBoroughs** [comment]
Can be solved by upgrading to "Supergroup"
https://telegramguide.com/what-is-telegram-supergroup/

**Comment by backmeupplz** [comment]
Should be working now.
