### ISSUE TITLE
Add link support in greeting messages

### ISSUE THREAD

**Issue by FiveBoroughs** [backmeupplz/shieldy#56]
Setting a greeting message with /greeting, like this one
![image](https://user-images.githubusercontent.com/40718516/71814024-264a5780-3073-11ea-92c7-2b799760b583.png)

Will result in this version being sent out
![image](https://user-images.githubusercontent.com/40718516/71814055-3f530880-3073-11ea-8bf3-3d708d7db348.png)

Missing the links and the markdown code formatting

**Comment by backmeupplz** [comment]
I'll have a look into how it can be done, thank you!
