### ISSUE TITLE
Inline bots messages sent during captcha timewindow are not deleted

### ISSUE THREAD

**Issue by FiveBoroughs** [backmeupplz/shieldy#58]
When a user joins, Shieldy will send a captcha, if the user fails the captcha, Shieldy will delete all messages the user sent and kick him.

Except when the user sends an inline bot message, like this one :
![image](https://user-images.githubusercontent.com/40718516/72220393-2bfade00-3548-11ea-8023-83f2b90375d3.png)
The captcha logic still works and the user is kicked, but the inline message is not deleted

**Comment by FiveBoroughs** [comment]
(No crash in the logs, unexpected message type I would guess)

**Comment by backmeupplz** [comment]
@FiveBoroughs does it happen with the /restrict and /strict on?

**Comment by backmeupplz** [comment]
Looks like I fixed it in https://github.com/backmeupplz/shieldy/commit/811a7b5b350dffe5b19cf25c517f00ab681e38a3, thank you for the report!

**Comment by FiveBoroughs** [comment]
Tested, that did it, thanks @backmeupplz
