### ISSUE TITLE
[Feature request] Add a /NoChannelLinks command

### ISSUE THREAD

**Issue by FiveBoroughs** [backmeupplz/shieldy#59]
Most of the spam I receive is from Bots linking to other groups:
![image](https://user-images.githubusercontent.com/40718516/72454523-ef81e900-37b8-11ea-8f39-be5c6dd901a2.png)

If there was a command I could activate to delete automatically any message that contains `t.me/*` it would reduce the amount of spam by 90%

**Comment by backmeupplz** [comment]
Thank you a lot for the suggestion! I feel like /restrict should cover this already
