### ISSUE TITLE
Bot isn't deleting entry/kick messages

### ISSUE THREAD

**Issue by naoliv** [backmeupplz/shieldy#64]
I didn't comment this on #52 to avoid polluting the issue with something possibly unrelated. 

Even with `/deleteEntryOnKick` we are still seeing both messages (`joined` and `removed`) in our channels:

![](https://user-images.githubusercontent.com/982338/73873307-22efea80-4830-11ea-8ba9-8b169846d181.png)

We've already tried to set the bot's permissions with as much permission as possible, but without success:

![](https://user-images.githubusercontent.com/982338/73873318-26837180-4830-11ea-973e-063c47766d6c.png)

Is there anything else that we need to set or try, please?

**Comment by FiveBoroughs** [comment]
Is the group Private ?

**Comment by naoliv** [comment]
They are public groups.
Originally they were created as super groups but it seems that now there isn't any kind of distinction anymore.

**Comment by backmeupplz** [comment]
Thanks, I'll investigate

**Comment by ilyakaznacheev** [comment]
Yep, same for me

**Comment by FiveBoroughs** [comment]
@naoliv and I diagnosed the problem in the said group, there was confusion between what the /deleteEntryOnKick and /deleteEntryMessage commands would do.
I guess better Commands Labels could have prevented this issue.

Do you have suggestions for better Brazilian translations Naoliv ?

**Comment by naoliv** [comment]
It seems that the bot's behavior is a little erratic.
For example, today we saw again the messages in another group:

![](https://user-images.githubusercontent.com/982338/74332272-2aede400-4d74-11ea-9c84-a115341f6dff.png)

`/deleteEntryOnKick` was already enabled (and you can see that after sending `/deleteEntryOnKick` the bot said it wouldn't remove the messages anymore)

Per the bot help, `/deleteEntryOnKick` is the right command to have the entry messages deleted:

`/deleteEntryOnKick — whether to delete entry messages for users who failed captcha`

Regardless if `/deleteEntryMessages` is enabled or not, it seems that `/deleteEntryOnKick` is still failing to delete some messages.

**Comment by backmeupplz** [comment]
Just tested, everything works fine. With `/deleteEntryMessages` Shieldy deletes all entry and left messages. With `/deleteEntryOnKick` Shieldy deletes entry and left messages for people who failed captcha.

**Comment by backmeupplz** [comment]
Found a bug, fixed it, behavior should not be erratic anymore. Thank you for the report!
