### ISSUE TITLE
Info for viewing all current configured options

### ISSUE THREAD

**Issue by KlausDevWalker** [backmeupplz/shieldy#65]
It would be nice if we can send something like `/info_config` and see all the options set at that moment. Cause when we try to see what is set, regularly we accidentally turn on/off/change the settings we don't want to change.

**Comment by backmeupplz** [comment]
Hm, sounds like a good feature, thank you for the suggestion

**Comment by KlausDevWalker** [comment]
You're pretty welcome :) BTW, Shieldy is getting better and better! It's my default catpcha bot by now :D Thanks for this excellent work :)

**Comment by backmeupplz** [comment]
Done! Now you can use the `/config` command to see the configuration :)

**Comment by KlausDevWalker** [comment]
Great, man! Thanks again! When this will begin to work on Shieldy? I'm firing this command in the group and also on PM with the bot, but I'm receiving nothing as output. Am I doing something wrong? 😅

**Comment by KlausDevWalker** [comment]
Nevermind. I saw in the code that the command is /viewConfig. 😅😅😅
