### ISSUE TITLE
Bot is not deleting messages in captcha mode

### ISSUE THREAD

**Issue by BenCat07** [backmeupplz/shieldy#69]
Basically, Strict mode is on, Captcha is used as authentication.
- User A joins.
- A sends some link to a scam site
- Bot Does not delete message until the user is kicked

Expected Behaviour:
- Bot deletes any messags that does not have to do with the captcha until they solved the captcha.

**Comment by backmeupplz** [comment]
Try giving Shieldy super admin right (all admin rights). Telegram seems to throttle non-super admins ability to delete messages and ban people for some reason. Please, reopen this issue if the issue persists.

**Comment by backmeupplz** [comment]
Also, try /restrict.
