### ISSUE TITLE
[Bug] customCaptchaMessage doesn't work with Digits Captcha

### ISSUE THREAD

**Issue by KlausDevWalker** [backmeupplz/shieldy#74]
I had made a few tests and noticed that when I select "Digits" Captcha and then set a customCaptchaMessage, even when it's on and showing me it will use my custom message, it doesn't. It uses the default message. I have a guess on that: all the other captcha types are compound, with two messages. "Digits" is not, placing the arithmetic operation in the same message as the captcha message. Maybe forcing the operation on another message would fix that. To feel less uncomfortable for so few characters in a message, I suggest forcing them to be as big/tall as they can. By the way, this is the only option blind-friendly that also defeat bots and userbots that only click a "I'm not a bot" button, killing two birds with one stone hahaha

**Comment by backmeupplz** [comment]
You have to use `$equation` and `$seconds` in custom captcha for the digits captcha.

**Comment by KlausDevWalker** [comment]
Marvelous! :) You're the best! :1st_place_medal:
