### ISSUE TITLE
[Bug] Custom captcha message doesn't evoke a mention if the new user doesn't have a username

### ISSUE THREAD

**Issue by KlausDevWalker** [backmeupplz/shieldy#75]
Using $fullname variable in a custom message won't evoke a mention. Is there a entity that doesn't care if the new user hasn't a username and mention him/her always? Some people that didn't solve the captcha said they didn't notice my group has this condition, probably cause they weren't mentioned. By the way, can you make available more variables to help further customization this message, like something related to the time that user joined the group?

**Comment by backmeupplz** [comment]
Thanks for noticing the bug, I'll fix it when I have time. I don't have any plans to add more variables.

**Comment by backmeupplz** [comment]
Should be fixed now.

**Comment by KlausDevWalker** [comment]
Bug terminated! I did some tests here and it's working greatly. Thanks again :D
