### ISSUE TITLE
Links aren't shown in captcha message and in the welcome message

### ISSUE THREAD

**Issue by MarcAnt01** [backmeupplz/shieldy#79]
Probably similar to https://github.com/backmeupplz/shieldy/issues/76 

Now there's no wrong highlighting, just not shown

**Comment by backmeupplz** [comment]
Just checked it — everything works. Please, provide a way to reproduce the issue or at least the content of `/viewConfig`. Thank you.

**Comment by backmeupplz** [comment]
Hm, welcome message works, but captcha doesn't use markdown. Worth investigating then.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/80865734-9f596480-8c8b-11ea-80f9-685a4c7472a5.png)
![image](https://user-images.githubusercontent.com/43090263/80865739-a2eceb80-8c8b-11ea-9d9e-b6cafcd0d6af.png)

**Comment by backmeupplz** [comment]
added support for formatted messages to the custom captcha messages, thank you for the suggestion :)
