### ISSUE TITLE
Spammers leaving messages are not deleted.

### ISSUE THREAD

**Issue by kworr** [backmeupplz/shieldy#81]
Suppose we have a spammer that joins channel and immediately leaves. If /deleteEntryOnKick is set bot shows the captcha and upon timeout removes captcha and entry message, but leaving message is still on the channel.

Example of bot usernames:
![зображення](https://user-images.githubusercontent.com/1639944/80916565-237e1b80-8d62-11ea-9ad9-7dbf90f2b825.png)

Proposal:
a) first read all pending messages in the group;
b) if /deleteEntryOnKick is set and user already left then remove both entry and part messages;
d) show captcha;
e) if user leaves without solving the captcha remove captcha immediately (and entry/part messages according to /deleteEntryOnKick).

Thanks in advance.

**Comment by KlausDevWalker** [comment]
You just need to use /strict and /restrict and you're good to go. :)

**Comment by kworr** [comment]
Well, according to `/viewConfig` both `strict` and `restrict` were `true`. Yet part message doesn't come directly from the user.

**Comment by KlausDevWalker** [comment]
Kinda strange. In my groups Shieldy is working like expected. One thing I noticed in your screenshot is that the $fullname's is kinda spammy and certainly is not trackable by Shieldy as such.

**Comment by backmeupplz** [comment]
From what I can see the issue is that `/deleteEntryOnKick` doesn't delete the message about the person leaving. I'll investigate, thank you for the report!

**Comment by backmeupplz** [comment]
`/deleteEntryOnKick` should now also delete the leaving messages on kick :)
