### ISSUE TITLE
Bot removes user messages after he passed captcha

### ISSUE THREAD

**Issue by anray** [backmeupplz/shieldy#83]
Bot is set to picture captcha mode and additionally /restrict and /strict.

1 min after user successfully passes captcha his text message with hashtags are removed.

**Comment by KlausDevWalker** [comment]
It's a intended action for /restrict where the new user only can post pure plain text in his/her first 24 hours.

**Comment by backmeupplz** [comment]
@KlausDevWalker thank you for describing this. Yes, this behavior is intended.
