### ISSUE TITLE
Bot isnt working

### ISSUE THREAD

**Issue by zodina34** [backmeupplz/shieldy#89]
Current config:

id: 852404243
language: en
captchaType: button
timeGiven: 120
adminLocked: false
restrict: false
noChannelLinks: false
deleteEntryMessages: false
greetsUsers: true
customCaptchaMessage: false
strict: true
deleteGreetingTime: 0
banUsers: false
deleteEntryOnKick: false
cas: true
underAttack: false
noAttack: true
buttonText: Not set
allowInvitingBots: false
greetingButtons:
Not set

**Comment by backmeupplz** [comment]
Please, make sure to configure the bot in the group and not in private messages :)
