### ISSUE TITLE
Add command to get the whole config as 1 string to setup Sheildy in one go, and not disturb groups

### ISSUE THREAD

**Issue by ianp5a** [backmeupplz/shieldy#90]
To avoid entering 10 or more commands and causing 20+ _annoying_ notifications in a group, the user could set up Sheildy with **1 command**. Using a proposed new _config string_, generated from an existing group or direct chat with Sheildy.

1. Start a chat directly with Shieldy
2. Enter all the commands as required
3. Enter the new command like /viewConfigString
4. Sheildy outputs a string of your config
5. Go to your group and enter the string as a command 
6. Or if that is not directly possible, enter a new command like: /inputConfigString  and wait for the response. Then enter the string when prompted.
7. After entering the the config string by method step 5 or 7, Shieldly confirms the new config is accepted. 

Also, the same command could be used to take the config from one group, and use it in another. This also saves remembering each setting that was previously used. Or for sharing with others who like your settings but are not familiar with the settings.

**Comment by backmeupplz** [comment]
I can see how it can be **extremely** confusing to anyone but power users and developers.

Feel free to delete the config messages in groups where they "annoy" users. Config works even after the messages are deleted.

However, maybe adding a command like `/setConfig restrict=true strict=false` can be useful, as well as generating it in the `/viewConfig` message.

**Comment by ianp5a** [comment]
Yes your suggestion of /setConfig one-liner would be a good solution. /viewConfig too, as it saves typing errors. That would certainly reduce the repeated notifications. 

The problem with these notifications is, some new group members can still be unsure of the group and as a result, turn off all notifications, or even leave. I delete each setup messages quickly, before members look to see if the notification is important for them.

**Comment by backmeupplz** [comment]
@ianp5a I'll implement `/setConfig` then, should be a good compromise between usability and fixing your issue :) Thank you for the report!

**Comment by backmeupplz** [comment]
You can now use /setConfig :) thank you again!
